### ISSUE TITLE
oi

### ISSUE THREAD

**Issue by luccaspaz** [LockDzn/rpg-character-sheet#1]
eu tô fazendo um rpg com meus amigos e eu tô a uma semana já correndo atrás de tentar fazer um site só que MEU DEUS COMO È DIFICIL
mas dai veio a luz na minha vida que foi esse codigo,
porem em algumas partes ele deu erro, poderia me ajudar e me dizer como montar?

**Comment by LockDzn** [comment]
Eu posso sim, so me falar o que deu erro

**Comment by luccaspaz** [comment]
> Eu posso sim, so me falar o que deu erro

eu só não entendo muito então devo ter montado o codigo todo errado dai o cite ficou com pouca coisa e tem parte que aparece até o codigo escrito como texto kkkkkkk
![2021-03-18 (1)](https://user-images.githubusercontent.com/80916061/111694833-29151080-8811-11eb-9d60-c8fdcb9157e6.png)

**Comment by LockDzn** [comment]
Você modificou o que no codigo?

**Comment by luccaspaz** [comment]
> Você modificou o que no codigo?

nada eu só nao consegui montar

**Comment by LockDzn** [comment]
Acho que você n baixou os arquivos do repositorio, so fazer isso:

![1](https://user-images.githubusercontent.com/28955729/112017628-8b6d5a00-8b0c-11eb-8a65-ed5f193c58f0.png)
![2](https://user-images.githubusercontent.com/28955729/112017661-958f5880-8b0c-11eb-9275-bf6e7f4208fe.png)

Depois só descompactar o zip que você baixou e iniciar o html
