### ISSUE TITLE
Dúvida

### ISSUE THREAD

**Issue by C4cko** [LockDzn/rpg-character-sheet#11]
Olá, teria alguma forma de eu ver o registro dos dados lançados pelos Jogadores? Assim como o Cellbit tem? Além disso, queria saber como salvar a vida e sanidade, além de textos e valores que são alterados ao longo do tempo. Como, em uma sessão, perdi 8 de vida e quero reduzir, como faço pra salvar?

**Comment by LockDzn** [comment]
Olá, esse codigo é so uma base de uma ficha de personagem, para salvar os registros dos dados, vida e sanidade você teria que usar um banco de dados.
