### ISSUE TITLE
Uma ajuda

### ISSUE THREAD

**Issue by AngelManu9** [LockDzn/rpg-character-sheet#13]
Como modifica o código pra só mostrar pra mim?
Tipo eu queria mudar os Status mas não consigo, aí tentei no code mas tava pedido pra enviar pelo pull

**Comment by pedrosegato** [comment]
baixa o código, abre ele com o Visual Studio Code, e ai vai mexendo até achar o que você quer mudar, se for o número de uma perícia vai tá no "characterSheet.js".

aí pra você abrir o site depois é só dar 2 cliques no "index.html" e abrir ele com o navegador
