### ISSUE TITLE
Ajuda aí pf

### ISSUE THREAD

**Issue by PepoGomes** [LockDzn/rpg-character-sheet#16]
Tem como eu salvar o site da ficha várias vezes pra personagens diferentes?
Como eu posso botar as perícias?
Gostaria de um tutorial de como programar as coisas da ficha. Pode me adicionar no discord se quiser pra conversar melhor.

**Comment by LockDzn** [comment]
Precisa de ter algumas noções de programação para fazer isso, não consigo fazer um tutorial para isso

**Comment by PepoGomes** [comment]
eu tô estudando um pouco.. Pode, por favor, me dar pelo menos o código pra criar as perícias?

**Comment by pedrosegato** [comment]
Cara, dá uma lida no código que você vai descobrir como adiciona uma perícia, não é nenhum pouco difícil.
