### ISSUE TITLE
Desculpa o incomodo

### ISSUE THREAD

**Issue by shad00m00** [LockDzn/rpg-character-sheet#18]
Eu sei que ce ta fazendo isso pra treinar e tudo mais
eu só queria saber mesmo se a função das armas estão normais ou não 
eu sou um muito leigo nesse assunto to indo atrás para tentar deixar do jeito que to pensando, mas essa questão das armas não tô conseguindo achar que tipo seria basicamente para rolar o dado da arma 
teria como ce confirmar isso para mim?
novamente, desculpe o incomodo

**Comment by LockDzn** [comment]
Para rolar o dado da arma não está funcionando, ainda não adicinei essa funcionalidade
