### ISSUE TITLE
Só uma duvida

### ISSUE THREAD

**Issue by Jovaah** [LockDzn/rpg-character-sheet#2]
Então, eu não sei se to fazendo algo errado, mas to tendo alguns problemas, por exemplo, quando eu tento testar algum atributo, aparece uma mensagem escrito 1 e mais nada, só o de aparência que funciona corretamente. Também não to conseguindo adicionar nenhuma perícia, assim, pode muito bem ser que eu to fazendo alguma coisa errada pq eu sou lesado

**Comment by LockDzn** [comment]
É que muitas funções não estão prontas
