### ISSUE TITLE
sou noob, ajuda

### ISSUE THREAD

**Issue by L0rian** [LockDzn/rpg-character-sheet#3]
eu baixei e abri a ficha no google, mas não da pra editar os números dos atributos e nem acrescentar perícia. eu preciso fazer alguma coisa ou é pq ainda nn ta pronto?

**Comment by jsblis89** [comment]
Eu acho que ainda não está pronto, pouco em pouco ele vai adicionar as
coisas

Em seg, 12 de abr de 2021 15:54, L0rian ***@***.***> escreveu:

**Comment by LockDzn** [comment]
L0rian, os dados do personagem está no arquivo characterSheet.js, na const data.
Só você mudar eles

![image](https://user-images.githubusercontent.com/28955729/114472508-b8bb9e00-9bc8-11eb-8742-986ffa1fd923.png)

**Comment by L0rian** [comment]
e como muda a foto do personagem? unica coisa q nn to conseguindo
