### ISSUE TITLE
sobre as pericias

### ISSUE THREAD

**Issue by L0rian** [LockDzn/rpg-character-sheet#5]
opa, ta dando tudo certo aqui, to conseguindo arrumar a maioria das coisas, mas não sei como coloca perícia. o que que tem que fazer?

**Comment by LockDzn** [comment]
Opa, para criar uma pericia você tem que mudar no codigo, mas vou adicionar uma forma de criar, excluir e editar pericias.

**Comment by delonnN** [comment]
Cara sério, se você realmente criar um modo de editar os números/adicionar novas perícias vc vai ser tipo meu deus. Uma dúvida, em todo o projeto você só usou HTML e CSS?

**Comment by LockDzn** [comment]
o HTML e CSS eu usei para criar o layout, as outras coisas foram com Javascript
