### ISSUE TITLE
Parabens

### ISSUE THREAD

**Issue by Lvkzera** [LockDzn/rpg-character-sheet#6]
Vey, na moral, ta foda teu trabalho
Por favor termina essa ficha de personagem
Se precisar de alguma info da ficha, eu te passo, por exemplo, as pericias que tem, os cálculos pra dar normal e etc., as outras abas de inventario como a de inventario, do dinheiro, etc.

**Comment by LockDzn** [comment]
Valeu mano :) pode mandar aqui as informações da ficha, vai ajudar muito

**Comment by Lvkzera** [comment]
Agora as Abas que ainda não tem nessa ficha que você fez.
Tem a aba de "Inventario" de cada um que possui um peso que cada um consegue carregar, com o peso máximo e atual, e cada slot de item possui seu respectivo peso.
Também possui uma aba de "Habilidades", que serve como se fosse um local pra anotação.
Tem uma aba chamada "Antecedentes", que nela possui "Descrição Pessoal", "Características", Ferimentos e Cicatrizes", "Fobias/Manias", "Pessoas Significativas", "Locais Importantes", "Pertences Queridos", "Tomos Arcanos, Feitiços e Artefatos" (Porem pode ser substituído por "Rituais" e "Encontro com Entidades Estranhas"

**Comment by Lvkzera** [comment]
Além disso possui um aba de "Dinheiro", que possui "Nível de Gastos", "Dinheiro" e "Patrimônio".
E também tem um local chamado "Anotações do Investigador", como o próprio nome diz, serve pros jogadores anotarem as coisas.
Ate onde eu sei possui essas informações nas fichas dos players, e caso queira tirar alguma duvida é só falar.

**Comment by LockDzn** [comment]
Valeu
