### ISSUE TITLE
Integração com websource do OBS

### ISSUE THREAD

**Issue by Kensyy** [LockDzn/rpg-character-sheet#8]
Minha pergunta ao desenvolvedor é, se caso teria no futuro uma maneira de integrar a ficha com uma web-source no OBS pra aparecer os dados da mesma forma que aparecem no RPG do Cellbit.

**Comment by LockDzn** [comment]
Da para fazer isso sim

**Comment by Kensyy** [comment]
Valeu, mas como funcionaria? ksjsk

**Comment by LockDzn** [comment]
Precisaria criar um servidor e conectar com web socket a ficha e uma pagina com as informações do personagem
