### ISSUE TITLE
uma duvida aq rapidão

### ISSUE THREAD

**Issue by axgflame** [LockDzn/rpg-character-sheet#9]
primeiramente parabéns, vc deve ter tido mt trabalho pra fazer esse código e eu admiro mt mesmo, ficou mt bom.
mas eu qria saber se tem como e onde q eu mudo o código de rolagem dos dados pra ver se eu consigo adequar no sistema do meu rpg, q é o d100

**Comment by LockDzn** [comment]
Valeu :) Cara, para fazer isso teria que mudar os dados no codigo

**Comment by axgflame** [comment]
tendi mano, mas eu n to achando os dados no código pra eu mudar kkkonde q fica
